<a href="https://colab.research.google.com/github/BAMBAMGit/crosswordMaker/blob/main/dictionary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [159]:
#@title Word Compare Function
# compares letters in a with letters in b. 
# ex, if a == *el*o & b == hello, return True; if a == *el*o & b == matza, return False
# word_compare("happy","ha***") returns True
def word_compare(a,b):
  if len(a) != len(b):
    return False
  for x in range(len(a)):
    if a[x] == b[x] or b[x] == "*":
      continue
    else:
      return False
  return True

In [ ]:
#@title Import Data Frame & processing
from pickle import FALSE
import numpy as np
import pandas as pd

from google.colab.data_table import DataTable
DataTable.max_columns = 50

dfA = pd.read_csv("A.csv", encoding="cp1252")
dfB = pd.read_csv("B.csv", encoding="cp1252")
dfC = pd.read_csv("C.csv", encoding="cp1252")
dfD = pd.read_csv("D.csv", encoding="cp1252")
dfE = pd.read_csv("E.csv", encoding="cp1252")
dfF = pd.read_csv("F.csv", encoding="cp1252")
dfG = pd.read_csv("G.csv", encoding="cp1252")
dfH = pd.read_csv("H.csv", encoding="cp1252")
dfI = pd.read_csv("I.csv", encoding="cp1252")
dfJ = pd.read_csv("J.csv", encoding="cp1252")
dfK = pd.read_csv("K.csv", encoding="cp1252")
dfL = pd.read_csv("L.csv", encoding="cp1252")
dfM = pd.read_csv("M.csv", encoding="cp1252")
dfN = pd.read_csv("N.csv", encoding="cp1252")
dfO = pd.read_csv("O.csv", encoding="cp1252")
dfP = pd.read_csv("P.csv", encoding="cp1252")
dfQ = pd.read_csv("Q.csv", encoding="cp1252")
dfR = pd.read_csv("R.csv", encoding="cp1252")
dfS = pd.read_csv("S.csv", encoding="cp1252")
dfT = pd.read_csv("T.csv", encoding="cp1252")
dfU = pd.read_csv("U.csv", encoding="cp1252")
dfV = pd.read_csv("V.csv", encoding="cp1252")
dfW = pd.read_csv("W.csv", encoding="cp1252")
dfX = pd.read_csv("X.csv", encoding="cp1252")
dfY = pd.read_csv("Y.csv", encoding="cp1252")
dfZ = pd.read_csv("Z.csv", encoding="cp1252")



# convert from object to string
dfA['column'] = dfA.astype('str')
dfB['column'] = dfB.astype('str')
dfC['column'] = dfC.astype('str')
dfD['column'] = dfD.astype('str')
dfE['column'] = dfE.astype('str')
dfF['column'] = dfF.astype('str')
dfG['column'] = dfG.astype('str')
dfH['column'] = dfH.astype('str')
dfI['column'] = dfI.astype('str')
dfJ['column'] = dfJ.astype('str')
dfK['column'] = dfK.astype('str')
dfL['column'] = dfL.astype('str')
dfM['column'] = dfM.astype('str')
dfN['column'] = dfN.astype('str')
dfO['column'] = dfO.astype('str')
dfP['column'] = dfP.astype('str')
dfQ['column'] = dfQ.astype('str')
dfR['column'] = dfR.astype('str')
dfS['column'] = dfS.astype('str')
dfT['column'] = dfT.astype('str')
dfU['column'] = dfU.astype('str')
dfV['column'] = dfV.astype('str')
dfW['column'] = dfW.astype('str')
dfX['column'] = dfX.astype('str')
dfY['column'] = dfY.astype('str')
dfZ['column'] = dfZ.astype('str')

df = pd.concat([dfA,
                dfB,
                dfC,
                dfD,
                dfE,
                dfF,
                dfG,
                dfH,
                dfI,
                dfJ,
                dfK,
                dfL,
                dfM,
                dfN,
                dfO,
                dfP,
                dfQ,
                dfR,
                dfS,
                dfT,
                dfU,
                dfV,
                dfW,
                dfX,
                dfY,
                dfZ,
                ])


df[['word', 'B']] = df['column'].str.split(" \(", 1, expand=True)
df[['C', 'definition']] = df['B'].str.split("\) ", 1, expand=True)
del df['B']
del df['C']
del df['column']
df = df.iloc[: , 26:]  # delete 1st column

df

In [207]:
compare_word = "S***t"
df['compare'] = df.apply(lambda x: word_compare(x['word'], compare_word), axis=1)
df[df["compare"] == True]

        word                                         definition  compare
60     Sabot  A kind of wooden shoe worn by the peasantry in...     True
61     Sabot  A thick, circular disk of wood, to which the c...     True
440    Saint  A person sanctified; a holy or godly person; o...     True
441    Saint                      One of the blessed in heaven.     True
442    Saint                       One canonized by the church.     True
...      ...                                                ...      ...
20723  Swift  Any one of numerous species of small, long-win...     True
20724  Swift  Any one of several species of lizards, as the ...     True
20725  Swift                   The ghost moth. See under Ghost.     True
20726  Swift  A reel, or turning instrument, for winding yar...     True
20727  Swift  The main card cylinder of a flax-carding machine.     True

[429 rows x 3 columns]